---
version: "3.7"
services:
  geocml-task-scheduler:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.geocml-task-scheduler
    image: ghcr.io/geocml/geocml-base-deployment:task-scheduler
    hostname: geocml-task-scheduler
    networks:
      - geocml-network
    volumes:
      - type: bind
        source: ./persistence-layer/DBBackups
        target: /DBBackups
  geocml-desktop:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.geocml-desktop
    image: ghcr.io/geocml/geocml-base-deployment:desktop
    ports:
      - "10000:10000"
    volumes:
      - type: bind
        source: ./persistence-layer
        target: /Persistence
    hostname: geocml-desktop
    networks:
      - geocml-network
  geocml-postgres:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.geocml-postgres
    image: ghcr.io/geocml/geocml-base-deployment:postgres
    ports:
      - "5432:5432"
    hostname: geocml-postgres
    networks:
      - geocml-network
  geocml-server:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.geocml-server
    image: ghcr.io/geocml/geocml-base-deployment:server
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./persistence-layer
        target: /Persistence
    hostname: geocml-server
    networks:
      - geocml-network
networks:
  geocml-network:
    external: true
    driver: bridge
...
