---
- # Configure xpra
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  tasks:
    - name: Make /run/user/0/xpra
      ansible.builtin.command: mkdir -p /run/user/0/xpra
    - name: Update xpra.conf
      ansible.builtin.command: sed -ie 's/^start-child/#start-child/' /etc/xpra/xpra.conf
