---
- # Configure geocml-server
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  tasks:
    - name: Enable cgid
      community.general.apache2_module:
        state: present
        name: cgid
        force: true
    - name: Enable fcgid
      community.general.apache2_module:
        state: present
        name: fcgid
        force: true
